version: '3'

services:
  ubuntu-box:
    build:
      context: .
      dockerfile: Containerfile
    container_name: ubuntu-box
    image: ubuntu-box:1.0
    hostname: ubuntu-box
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: sleep infinity
    working_dir: /home/${IMAGE_USER}
    user: ${IMAGE_USER}
    userns_mode: keep-id
    environment:
      - UID=1000
      - GID=1000
      - SHELL=/bin/zsh
      - EDITOR=vim
    volumes:
      - ./shared:/home/${IMAGE_USER}/shared:z
      - ~/.ssh:/home/${IMAGE_USER}/.ssh:ro,Z
